import Head from 'next/head';
import Image from 'next/image';
import { FormEvent, useEffect, useState } from 'react';

import { Product, getProducts } from '@/utils/getProducts';

export default function Home() {
  const [search, setSearch] = useState('');
  const [products, setProducts] = useState([]);

  const handleSubmit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); // Prevent the default form submission behavior

    try {
      const newProducts = await getProducts(search);
      setProducts(newProducts);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Amazon Search Box</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>

      <main className='container mt-6 px-8'>
        <form onSubmit={handleSubmit}>
          <input
            type='text'
            className='w-full rounded-lg border-2 border-gray-200 bg-gray-200
         px-4 py-2 transition-all focus:border-gray-500 focus:outline-none'
            value={search}
            placeholder='Search for a product...'
            onChange={(e) => {
              e.preventDefault();
              setSearch(e.target.value);
            }}
          />
        </form>
        <div className='mt-6 grid grid-cols-3 gap-4'>
          {products &&
            products?.length > 0 &&
            products?.map((product: Product, i) => (
              <ProductCard product={product} key={i} />
            ))}
        </div>
      </main>
    </>
  );
}

const ProductCard = ({ product, ...props }: { product: Product }) => (
  <div
    className='flex flex-col justify-between rounded-lg bg-white p-4 shadow-lg'
    {...props}
  >
    <div className='flex justify-center'>
      <Image
        src={product.image}
        alt={product.title}
        className='h-32 w-32 object-contain'
        width={128}
        height={128}
      />

      <div className='ml-4'>
        <h2 className='text-lg font-bold'>{product.title}</h2>
        <p className='text-sm text-gray-500'>{product.price}</p>
      </div>
    </div>
  </div>
);
